package com.example.boo345word.ui.word

import androidx.annotation.DrawableRes
import com.example.boo345word.R

enum class WordSymbols(
    val english: String,
    @DrawableRes
    val symbol: Int
) {
    AIRCRAFT_CARRIER("aircraft carrier", R.drawable.aircraft_carrier),
    AIRPLANE("airplane", R.drawable.airplane),
    ALARM_CLOCK("alarm clock", R.drawable.alarm_clock),
    AMBULANCE("ambulance", R.drawable.ambulance),
    ANGEL("angel", R.drawable.angel),
    ANIMAL_MIGRATION("animal migration", R.drawable.animal_migration),
    ANT("ant", R.drawable.ant),
    ANVIL("anvil", R.drawable.anvil),
    APPLE("apple", R.drawable.apple),
    ARM("arm", R.drawable.arm),
    ASPARAGUS("asparagus", R.drawable.asparagus),
    AXE("axe", R.drawable.axe),
    BACKPACK("backpack", R.drawable.backpack),
    BANANA("banana", R.drawable.banana),
    BANDAGE("bandage", R.drawable.bandage),
    BARN("barn", R.drawable.barn),
    BASEBALL_BAT("baseball bat", R.drawable.baseball_bat),
    BASEBALL("baseball", R.drawable.baseball),
    BASKET("basket", R.drawable.basket),
    BASKETBALL("basketball", R.drawable.basketball),
    BAT("bat", R.drawable.bat),
    BATHTUB("bathtub", R.drawable.bathtub),
    BEACH("beach", R.drawable.beach),
    BEAR("bear", R.drawable.bear),
    BEARD("beard", R.drawable.beard),
    BED("bed", R.drawable.bed),
    BEE("bee", R.drawable.bee),
    BELT("belt", R.drawable.belt),
    BENCH("bench", R.drawable.bench),
    BICYCLE("bicycle", R.drawable.bicycle),
    BINOCULARS("binoculars", R.drawable.binoculars),
    BIRD("bird", R.drawable.bird),
    BIRTHDAY_CAKE("birthday cake", R.drawable.birthday_cake),
    BLACKBERRY("blackberry", R.drawable.blackberry),
    BLUEBERRY("blueberry", R.drawable.blueberry),
    BOOK("book", R.drawable.book),
    BOOMERANG("boomerang", R.drawable.boomerang),
    BOTTLECAP("bottlecap", R.drawable.bottlecap),
    BOWTIE("bowtie", R.drawable.bowtie),
    BRACELET("bracelet", R.drawable.bracelet),
    BRAIN("brain", R.drawable.brain),
    BREAD("bread", R.drawable.bread),
    BRIDGE("bridge", R.drawable.bridge),
    BROCCOLI("broccoli", R.drawable.broccoli),
    BROOM("broom", R.drawable.broom),
    BUCKET("bucket", R.drawable.bucket),
    BULLDOZER("bulldozer", R.drawable.bulldozer),
    BUS("bus", R.drawable.bus),
    BUSH("bush", R.drawable.bush),
    BUTTERFLY("butterfly", R.drawable.butterfly),
    CACTUS("cactus", R.drawable.cactus),
    CAKE("cake", R.drawable.cake),
    CALCULATOR("calculator", R.drawable.calculator),
    CALENDAR("calendar", R.drawable.calendar),
    CAMEL("camel", R.drawable.camel),
    CAMERA("camera", R.drawable.camera),
    CAMOUFLAGE("camouflage", R.drawable.camouflage),
    CAMPFIRE("campfire", R.drawable.campfire),
    CANDLE("candle", R.drawable.candle),
    CANNON("cannon", R.drawable.cannon),
    CANOE("canoe", R.drawable.canoe),
    CAR("car", R.drawable.car),
    CARROT("carrot", R.drawable.carrot),
    CASTLE("castle", R.drawable.castle),
    CAT("cat", R.drawable.cat),
    CEILING_FAN("ceiling fan", R.drawable.ceiling_fan),
    CELL_PHONE("cell phone", R.drawable.cell_phone),
    CELLO("cello", R.drawable.cello),
    CHAIR("chair", R.drawable.chair),
    CHANDELIER("chandelier", R.drawable.chandelier),
    CHURCH("church", R.drawable.church),
    CIRCLE("circle", R.drawable.circle),
    CLARINET("clarinet", R.drawable.clarinet),
    CLOCK("clock", R.drawable.clock),
    CLOUD("cloud", R.drawable.cloud),
    COFFEE_CUP("coffee cup", R.drawable.coffee_cup),
    COMPASS("compass", R.drawable.compass),
    COMPUTER("computer", R.drawable.computer),
    COOKIE("cookie", R.drawable.cookie),
    COOLER("cooler", R.drawable.cooler),
    COUCH("couch", R.drawable.couch),
    COW("cow", R.drawable.cow),
    CRAB("crab", R.drawable.crab),
    CRAYON("crayon", R.drawable.crayon),
    CROCODILE("crocodile", R.drawable.crocodile),
    CROWN("crown", R.drawable.crown),
    CRUISE_SHIP("cruise ship", R.drawable.cruise_ship),
    CUP("cup", R.drawable.cup),
    DIAMOND("diamond", R.drawable.diamond),
    DISHWASHER("dishwasher", R.drawable.dishwasher),
    DIVING_BOARD("diving board", R.drawable.diving_board),
    DOG("dog", R.drawable.dog),
    DOLPHIN("dolphin", R.drawable.dolphin),
    DONUT("donut", R.drawable.donut),
    DOOR("door", R.drawable.door),
    DRAGON("dragon", R.drawable.dragon),
    DRESSER("dresser", R.drawable.dresser),
    DRILL("drill", R.drawable.drill),
    DRUMS("drums", R.drawable.drums),
    DUCK("duck", R.drawable.duck);

    companion object {
        fun find(english: String): Int? {
            return entries.find { it.english == english }?.symbol
        }
    }
}
